### ISSUE TITLE
Facebook post missing favicon on churchapps website

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#294] opened 2024-05-28 15:15 UTC
<img width="1481" alt="Screenshot 2024-05-28 at 10 15 15 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/89a6baef-aea5-4fb4-b1c6-82a2e6dde73a">

**Comment by mbyrdLCS** [comment] 2024-06-04 14:46
Thank you I did not realize I did not have that in there. I added one and gave it an hour I am still not seeing it on the facebook debug page. I made 2 
![church apps 21200 X 630](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/89a0b11a-299b-4aed-acac-e82b368ae4e4)
![church apps 1200 X 630](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/0a174880-20e3-4607-a6b5-8161a411ecec)

**Comment by Himali-Malvawala** [comment] 2024-07-24 06:48
I believe the link now shows the correct logo. So I'm closing the issue.

**Comment by mbyrdLCS** [comment] 2024-07-24 14:12
This is still not showing up correctly here [their portal](https://developers.facebook.com/tools/debug)

**Comment by mbyrdLCS** [comment] 2024-07-29 23:10
<img width="1512" alt="Screenshot 2024-07-29 at 5 08 19 PM" src="https://github.com/user-attachments/assets/6ac78e54-99e4-4ead-97b4-1c9fe691871c">

This is still an issue and I would like to get it fixed I have the Favicon correctly uploaded but it is not showing up on facebook post. https://arkcurriculum.com/ is the website on B1

**Comment by Himali-Malvawala** [comment] 2024-07-30 10:56
It looks like Facebook is still showing the old cached version of the image, cause when we upload a new image we update the og:image tag in our source code. 

So when we inspect the website, the tag og:image, it is showing the correct value
![image](https://github.com/user-attachments/assets/5b85c6bd-6278-4f79-ba57-e10d8230b065)
![image](https://github.com/user-attachments/assets/9dd8e24d-de59-4dc3-920d-eedd98ab2927)

**Comment by vassbo** [comment] 2024-07-30 11:29
I think it might show, but because the text in the image is white and and the background is white, you can't see the logo. Try uploading a new image with a dark background!

**Comment by mbyrdLCS** [comment] 2024-07-30 14:40
<img width="1512" alt="Screenshot 2024-07-30 at 8 39 03 AM" src="https://github.com/user-attachments/assets/a36dc84d-df50-436c-9039-b417b7cad5e9">

Originally I think you are right but it was updated Like [Himali-Malvawala](https://github.com/Himali-Malvawala) is saying I dont think it is updating causing issues with this site and churchapps same issue.

**Comment by vassbo** [comment] 2024-07-30 16:03
Okay, Facebook gives a warning when scraping, maybe it can't find the new 'og:image' tag:
![bilde](https://github.com/user-attachments/assets/b307f4c6-92c1-4416-ba79-37c1c048c8fd)

I found this issue: https://stackoverflow.com/a/71124242
My guess is that there's too much data caused by the <style> tags before the meta tag, so we can try moving it at the top of the <head>.
I also tried a bunch of different Open Graph validators, and almost none of them where able to find the meta tag even though it is there!

**Comment by Himali-Malvawala** [comment] 2024-07-31 10:16
I've moved just the og:image tag to the top for now. I haven't pushed it to production but we can test it on staging.

I tried scraping [https://testing24.staging.b1.church/](https://testing24.staging.b1.church/) on Facebook Debugger but it's still showing the old version. 

![image](https://github.com/user-attachments/assets/d5ead9a4-7de4-423b-8341-b7ce80f241cd)
![testing24-staging-FB](https://github.com/user-attachments/assets/0d054c8c-74f5-4774-8a72-3c8cb8163f14)

**Comment by vassbo** [comment] 2024-07-31 10:33
Strange, I guess it's defaulting to the first `<img>` tag on the page then.
It looks like Facebook automatically assigned the other tags as well, but we can try adding the other required tags manually to the head as well, maybe it needs all of them to use one: https://ogp.me/#metadata

**Comment by Himali-Malvawala** [comment] 2024-08-01 06:47
Added all the required tags to the staging, but still no luck.

**Comment by vassbo** [comment] 2024-08-01 07:08
Okay, Facebook is not going to wait for all the content to load, so my last guess then is that the code that adds the meta tags to the head are not loaded in time for Facebook execute it!

Click on this to see what code Facebook has read, the OG tags are not there:
![bilde](https://github.com/user-attachments/assets/0de1c7f6-0768-4f8e-827a-925f2b1e9985)

**Comment by Himali-Malvawala** [comment] 2024-08-02 10:42
@vassbo @mbyrdLCS It's Fixed! 🎉

Pushing it to production now.

**Comment by mbyrdLCS** [comment] 2024-08-07 01:14
I am sorry I am not seeing that it is fixed am I missing something? 

<img width="1512" alt="Screenshot 2024-08-06 at 7 13 35 PM" src="https://github.com/user-attachments/assets/93363da7-ff48-4471-a837-9fbe4e57082c">

**Comment by Himali-Malvawala** [comment] 2024-08-07 09:24
Sorry, it wasn't pushed to production. But Jeremy just did it. So it should work now.

**Comment by vassbo** [comment] 2024-08-07 14:58
I guess there's a way to auto crop the images, but generally it's recommended to use an image size with 1.91:1 aspect ratio (then it should show up correctly on both small & big screens): https://developers.facebook.com/docs/sharing/webmasters/images/

I see it's noted here in the button to upload Open Graph images as well (1200x630 pixels): https://github.com/ChurchApps/ChurchAppsSupport/issues/294#issuecomment-2147290111

**Comment by mbyrdLCS** [comment] 2024-08-07 15:09
its pulling the top image but it should be pulling the bottom right red words correct?

**Comment by vassbo** [comment] 2024-08-07 15:58
Not sure how it chooses between the different images, you can probably answer better than I @Himali-Malvawala?

**Comment by Himali-Malvawala** [comment] 2024-08-07 16:28
Yes, as pointed out by @vassbo, the recommended ratio is 1.91:1 (1200 x 630), and we have a separate uploader for that. Facebook is pulling the right image (bottom left).

About pulling the favicon (bottom right), it's 400 x 400, so it won't support the larger images. However, I guess we can try to add width and height to make sure the image size is correct.
![image](https://github.com/user-attachments/assets/77f03e67-7e24-4fac-9d76-af06a3730d77)

**Comment by mbyrdLCS** [comment] 2024-08-22 13:34
I’m a bit confused—when I post it, the favicon isn’t showing up as expected. Am I missing something?

<img width="1394" alt="Screenshot 2024-08-22 at 7 29 20 AM" src="https://github.com/user-attachments/assets/c93f64d1-9152-4545-966d-1007cd844400">

<img width="1394" alt="Screenshot 2024-08-22 at 7 31 05 AM" src="https://github.com/user-attachments/assets/89450137-cc68-499a-9803-74f9d31d4e69">

<img width="1241" alt="Screenshot 2024-08-22 at 7 27 46 AM" src="https://github.com/user-attachments/assets/6ebfba5c-7fbb-4c51-af50-a7396c608379">

**Comment by Himali-Malvawala** [comment] 2024-08-22 17:56
As I mentioned, what you upload for the ogImage will be displayed. This means you have a transparent logo as the ogImage. So Facebook is showing the correct image.
![image](https://github.com/user-attachments/assets/24a2b735-cd92-4158-8d54-c652f756adc3)

**Comment by jzongker** [comment] 2024-11-01 19:41
I believe this issue is resolved, so I'm closing it.  Please re-open if that's not correct.

**Closed by jzongker** 2024-11-01 19:41 UTC
Labels: design, urgent, enhancement
