### ISSUE TITLE
Can't reposition pages

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#378] opened 2024-09-20 16:49 UTC
Some of the pages in the main navigation and not linked pane will not move. The top ones work ok but when you go down they will not move. 

https://github.com/user-attachments/assets/50c8280d-3fc9-4e50-b9cc-1fbac2cc526d

**Comment by Himali-Malvawala** [comment] 2024-09-21 08:58
@tbyrd77 When you try to move the links, can you keep the console tab open on the side? I guess there might be an error.

**Comment by jzongker** [comment] 2024-09-21 16:32
@tbyrd77 - I'm unable to reproduce this on the same account.  Can you try closing and re-opening your browser to see if that fixes it?  If not, please let me know which browser and OS you're using and I'll try with the same combo.

https://github.com/user-attachments/assets/7f2b8b4a-64f1-4800-812c-5f9bdbf0fc46

**Comment by tbyrd77** [comment] 2024-09-23 04:50
It is working now. I’m not sure what the problem was. You can close the issue. Thanks

**Closed** 2024-09-23 05:16 UTC
Labels: b1, urgent
