### ISSUE TITLE
Logos do not look correct in Safari

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#356] opened 2024-08-14 18:22 UTC
Logos do not look correct in Safari

<img width="1374" alt="Screenshot 2024-08-14 at 12 17 14 PM" src="https://github.com/user-attachments/assets/eca33098-0b2f-400a-8bb2-6b38913188f6">

**Comment by Himali-Malvawala** [comment] 2024-08-14 19:21
Duplicate of [#223](https://github.com/ChurchApps/ChurchAppsSupport/issues/223)

**Closed by Himali-Malvawala** 2024-08-14 19:21 UTC
Labels: b1
